name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update Rust
      run: |
        apt-get update
        apt-get upgrade
        rustup update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
