name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings
  RUSTFLAGS: "-Dwarnings"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Check With Clipy
      run: cargo clippy --all-features
    - name: Run tests
      run: cargo test --verbose
